@vamshi added report folder

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -19,10 +19,26 @@ jobs:
       run: npx playwright install --with-deps
     - name: Run Playwright tests
       run: npm run test:regression
+    - name: Debug Check if Allure results exist
+      run: |
+          if [ ! -d "allure-results" ]; then
+            echo "ERROR: allure-results directory not found!"
+            exit 1
+          fi
+          echo "Allure results exist."
+
     - name: Generate Allure Report
       run: |
           npm install -g allure-commandline
           allure generate allure-results --clean -o allure-report
+
+    - name: Check if Allure report exists
+      run: |
+          if [ ! -d "allure-report" ]; then
+            echo "ERROR: allure-report directory not found!"
+            exit 1
+          fi
+          echo "Allure report generated successfully."
 
     - name: Deploy Allure Report to GitHub Pages
       run: |
@@ -35,3 +51,4 @@ jobs:
           git add .
           git commit -m "Deploy Allure report"
           git push -f https://${{ secrets.GH_PAT }}@github.com/automation9006/typescript-cocktail-api-tests.git gh-pages
+
